//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcuSyrinxAPI.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TH_PURCHASE_INVOICES> TH_PURCHASE_INVOICES { get; set; }
        public virtual DbSet<TH_PURCHASE_INV_LINES> TH_PURCHASE_INV_LINES { get; set; }
        public virtual DbSet<TH_HIRE_INV_LINES> TH_HIRE_INV_LINES { get; set; }
        public virtual DbSet<TH_HIRE_INVOICES> TH_HIRE_INVOICES { get; set; }
    }
}
