//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcuSyrinxAPI.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_HIRE_INV_LINES
    {
        public int IVL_INVOICE_NUMBER { get; set; }
        public int IVL_SEQ { get; set; }
        public string IVL_DETAILS { get; set; }
        public string IVL_NOMINAL_LEDGER_CODE { get; set; }
        public string IVL_TAX_CODE { get; set; }
        public Nullable<int> IVL_LINE_SITE_ID { get; set; }
        public Nullable<int> IVL_ADVNOTE_HIRE_CONTRACT_ID { get; set; }
        public Nullable<int> IVL_CONTRACT_NUMBER { get; set; }
        public Nullable<System.DateTime> IVL_DATE_FROM { get; set; }
        public Nullable<System.DateTime> IVL_DATE_TO { get; set; }
        public string IVL_CUSTOMER_REFERENCE { get; set; }
        public Nullable<decimal> IVL_CHARGE { get; set; }
        public Nullable<float> IVL_LINE_TAX_RATE { get; set; }
        public Nullable<decimal> IVL_TAX_AMOUNT { get; set; }
        public Nullable<decimal> IVL_GENERATED_CHARGE { get; set; }
        public bool IVL_EXCLUDE { get; set; }
        public Nullable<float> IVL_DISCOUNT_PCT { get; set; }
        public Nullable<decimal> IVL_PRE_DISCOUNT_CHARGE { get; set; }
        public Nullable<int> IVL_SECTION_NO { get; set; }
        public string IVL_QUANTITY { get; set; }
        public Nullable<decimal> IVL_UNIT_PRICE { get; set; }
        public string IVL_NOTES { get; set; }
        public byte[] upsize_ts { get; set; }
        public string IVL_NOTES2 { get; set; }
        public Nullable<int> IVL_SOURCEDOC_ID { get; set; }
        public Nullable<int> IVL_SOURCEDOC_LINE_SEQ { get; set; }
        public string IVL_LOCAL_TAX_CODE { get; set; }
        public Nullable<float> IVL_LOCAL_TAX_RATE { get; set; }
        public Nullable<decimal> IVL_LOCAL_TAX_AMOUNT { get; set; }
        public string IVL_STOCK_NO { get; set; }
        public string IVL_PRICE_PER { get; set; }
        public Nullable<int> IVL_HIRE_DURATION_PERIODS { get; set; }
        public Nullable<float> IVL_HIRE_DURATION_ADD_DAYS { get; set; }
        public Nullable<decimal> IVL_1DAY_RATE { get; set; }
        public Nullable<int> IVL_HIRE_STATUS { get; set; }
        public Nullable<System.DateTime> IVL_HIRE_OFFHIRE_DATE { get; set; }
        public bool IVL_USER_MODIFIED { get; set; }
        public string IVL_CURR_EQUIPMENT_CODE { get; set; }
        public string IVL_CURR_STOCKNO { get; set; }
        public Nullable<bool> IVL_IS_FIRST_HIRE_INV { get; set; }
    
        public virtual TH_HIRE_INVOICES TH_HIRE_INVOICES { get; set; }
    }
}
