//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcuSyrinxAPI.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TH_PURCHASE_INV_LINES
    {
        public int PIL_INVOICE_ID { get; set; }
        public int PIL_SEQ { get; set; }
        public string PIL_NOMINAL_CODE { get; set; }
        public string PIL_DESCRIPTION { get; set; }
        public Nullable<decimal> PIL_NET_AMOUNT { get; set; }
        public string PIL_TAX_CODE { get; set; }
        public Nullable<decimal> PIL_TAX_AMOUNT { get; set; }
        public Nullable<int> PIL_EVENT_ID { get; set; }
        public string PIL_ACCOUNTS_DEPT { get; set; }
    
        public virtual TH_PURCHASE_INVOICES TH_PURCHASE_INVOICES { get; set; }
    }
}
